"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
"""
def findTheDifference(s, t):
    letters = "abcdefghijklmnopqrstuvwxyz"
    for x in letters:
        if s.count(x) != t.count(x):
            return x
    #Or Use Hash Mapping
